In [2]:
import numpy as np
# numpy version : 
np.__version__

'1.26.4'

In [13]:
import sys

## 1. Defining arrays : 

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
a.size

4

In [5]:
a.shape

(4,)

In [6]:
a.dtype

dtype('int32')

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

## 2. Data Types : 

In [15]:
a = np.array([1, 2, 3, 4], dtype="uint8")
sys.getsizeof(a)

116

In [16]:
a = np.array([1, 2, 3, 4], dtype="int16")
sys.getsizeof(a)

120

In [17]:
a = np.array([1, 2, 3, 4], dtype="int32")
sys.getsizeof(a)

128

In [19]:
b = np.array([1, 2, 3, 4.0])
print(b.dtype)
sys.getsizeof(b)

float64


144

In [21]:
b = np.array([1, 2, 3, 4.0], dtype="float32")
sys.getsizeof(b)

128

In [22]:
c = np.array([111, 222, 333, 444], dtype="uint8")
c

C:\Users\maichi\AppData\Local\Temp\ipykernel_13540\295331409.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 333 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  c = np.array([111, 222, 333, 444], dtype="uint8")
C:\Users\maichi\AppData\Local\Temp\ipykernel_13540\295331409.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 444 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  c = np.array([111, 222, 333, 444], dtype="uint8")


array([111, 222,  77, 188], dtype=uint8)

## 3. 2D Arrays : 

In [24]:
d = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])
d.shape

(3, 3)

In [25]:
d.size

9

In [26]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 4.  Zeros and Ones : 

In [27]:
a = np.ones((3, 4), dtype="uint32")